
import React from 'react';
import { 
  LayoutDashboard, 
  MessageSquare, 
  BarChart3, 
  Settings, 
  Users, 
  Bell, 
  Search, 
  ArrowUpRight, 
  ArrowDownRight,
  Send,
  Sparkles,
  Command,
  Zap,
  Layers,
  MoreVertical,
  Plus,
  Briefcase,
  Calendar,
  Shield,
  Cpu,
  Clock,
  ExternalLink,
  ChevronRight,
  CheckCircle2,
  AlertCircle
} from 'lucide-react';

export const Icons = {
  Dashboard: LayoutDashboard,
  Chat: MessageSquare,
  Stats: BarChart3,
  Settings: Settings,
  Users: Users,
  Notifications: Bell,
  Search: Search,
  TrendUp: ArrowUpRight,
  TrendDown: ArrowDownRight,
  Send: Send,
  AI: Sparkles,
  Command: Command,
  Zap: Zap,
  Layers: Layers,
  More: MoreVertical,
  Plus: Plus,
  Project: Briefcase,
  Calendar: Calendar,
  Security: Shield,
  System: Cpu,
  Clock: Clock,
  External: ExternalLink,
  Next: ChevronRight,
  Success: CheckCircle2,
  Alert: AlertCircle
};
